name: memo_wall.dev
on:
  push:
    branches:
      - 'master'
      - 'production'
  workflow_dispatch:

env:
  POSTGRES_DB: test_memo_wall
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install 
          yarn knex migrate:latest --env test
          cd test
          yarn jest ./UserController.test.ts
        working-directory: ./WSP005
  # deploy:
  #     if: github.ref_name == 'production'
  #     runs-on: ubuntu-latest
  #     needs: testing
  #     steps:
  #     - name: ssh to pull latest version
  #       uses: fifsky/ssh-action@master
  #       with:
  #         command: |
  #           cd tecky-exercises\WSP005
  #           git pull origin main
  #           yarn install
  #           yarn knex migrate:latest --env production
  #           forever restart index.js
  #         host: c22sw.tecky.dev
  #         user: ubuntu
  #         key: ${{secrets.SSH_PRIVATE_KEY}}




# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "master" branch
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
